name: Jevlis Ka?
description: A new Flutter project!

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutterflow_ui: '^0.2.0+1'
  google_fonts: '^4.0.3'
  simple_gradient_text: '^1.3.0'

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.27.0

  flutter_animate: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
